package com.FuBangkun.tothestarsremake.asm;

import com.google.common.eventbus.EventBus;
import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.relauncher.IFMLLoadingPlugin.MCVersion;

import java.util.Collections;

@MCVersion("1.12.2")
public class TTSModContainer extends DummyModContainer {
	public TTSModContainer() {
		super(new ModMetadata());
		ModMetadata meta = this.getMetadata();
		meta.modId = "tothestarsremakecore";
		meta.name = "ToTheStarsRemake Core";
		meta.version = "1.0.0";
		meta.description = "The coremod for ToTheStarsRemake.";
		meta.authorList = Collections.singletonList("FuBangkun");
		meta.url = "";
		meta.autogenerated = false;
	}
	
	@Override
	public boolean registerBus(EventBus bus, LoadController controller) {
		bus.register(this);
		return true;
	}
}
